#!/usr/bin/env bash
#
# hermes-web-ui watchdog — automatic crash recovery with self-healing
#
# Three-phase recovery:
#   Phase 1: Fast restart (simple crashes)
#   Phase 2: Auto-diagnose + targeted fix (known patterns)
#   Phase 3: Write diagnostic report for agent (unknown errors)
#
# Usage:
#   ./watchdog.sh [options]
#
# Options:
#   --port PORT        Web-UI port (default: 8648)
#   --interval SEC     Check interval in seconds (default: 30)
#   --max-retries N    Max Phase 1 restart attempts (default: 3)
#   --log-dir DIR      Log directory (default: ~/.hermes-web-ui/logs)
#   --restart-cmd CMD  Custom restart command
#   --state-file PATH  Persistent state (default: ~/.hermes-web-ui/watchdog-state)
#

set -euo pipefail

# --- Defaults ---
PORT="${PORT:-8648}"
CHECK_INTERVAL="${CHECK_INTERVAL:-30}"
MAX_RETRIES="${MAX_RETRIES:-3}"
LOG_DIR="${LOG_DIR:-$HOME/.hermes-web-ui/logs}"
STATE_FILE="${STATE_FILE:-$HOME/.hermes-web-ui/watchdog-state}"
RESTART_CMD="${RESTART_CMD:-}"
HEALTH_URL="http://127.0.0.1:${PORT}/health"
MAINTENANCE_FILE="$HOME/.hermes-web-ui/.maintenance"

# --- Phase 2 config ---
DIAGNOSIS_DONE_FILE="$HOME/.hermes-web-ui/.diagnosis-done"
PHASE2_MAX_DIAGNOSES=3  # Max diagnoses in 24h before permanent stop

# --- Parse CLI args ---
while [[ $# -gt 0 ]]; do
    case $1 in
        --port) PORT="$2"; HEALTH_URL="http://127.0.0.1:${PORT}/health"; shift 2 ;;
        --interval) CHECK_INTERVAL="$2"; shift 2 ;;
        --max-retries) MAX_RETRIES="$2"; shift 2 ;;
        --log-dir) LOG_DIR="$2"; shift 2 ;;
        --restart-cmd) RESTART_CMD="$2"; shift 2 ;;
        --state-file) STATE_FILE="$2"; shift 2 ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

# --- Setup ---
mkdir -p "$LOG_DIR" "$(dirname "$STATE_FILE")"
CRASH_SIGNAL="$LOG_DIR/CRASH_SIGNAL"
CONSECUTIVE_FAILURES=0
TOTAL_FAILURES_TODAY=0
PHASE2_COUNT=0

# Load persistent state
if [[ -f "$STATE_FILE" ]]; then
    # shellcheck source=/dev/null
    source "$STATE_FILE" 2>/dev/null || true
fi

# Reset daily counter (check if last reset was today)
TODAY=$(date '+%Y-%m-%d')
if [[ "${LAST_RESET_DATE:-}" != "$TODAY" ]]; then
    TOTAL_FAILURES_TODAY=0
    PHASE2_COUNT=0
fi

save_state() {
    cat > "$STATE_FILE" <<EOF
# Auto-generated by watchdog — do not edit
TOTAL_FAILURES_TODAY=$TOTAL_FAILURES_TODAY
PHASE2_COUNT=$PHASE2_COUNT
LAST_RESET_DATE=$TODAY
LAST_CRASH_TIME=${LAST_CRASH_TIME:-0}
EOF
}

# --- Functions ---
timestamp() { date '+%Y-%m-%d %H:%M:%S'; }

log() {
    echo "[$(timestamp)] [watchdog] $*"
}

is_maintenance_mode() {
    [[ -f "$MAINTENANCE_FILE" ]]
}

check_process_alive() {
    pgrep -f "hermes-web-ui.*dist/server" >/dev/null 2>&1
}

check_health() {
    local http_code
    http_code=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout 5 --max-time 10 "$HEALTH_URL" 2>/dev/null || echo "000")
    [[ "$http_code" == "200" ]]
}

wait_for_port_free() {
    local max_wait=10
    local waited=0
    while [[ $waited -lt $max_wait ]]; do
        if ! lsof -i :"$PORT" >/dev/null 2>&1; then
            return 0
        fi
        sleep 1
        waited=$((waited + 1))
    done
    log "⚠️  Port $PORT still occupied after ${max_wait}s"
    return 1
}

save_crash_log() {
    local reason="$1"
    local phase="$2"
    local timestamp_str
    timestamp_str=$(date '+%Y-%m-%dT%H-%M-%S')
    local crash_log="$LOG_DIR/crash-${timestamp_str}.log"

    {
        echo "=== Crash Report ==="
        echo "Time: $(timestamp)"
        echo "Reason: $reason"
        echo "Phase: $phase"
        echo ""
        echo "--- Process Status ---"
        ps aux | grep -E "hermes-web-ui|node.*${PORT}" | grep -v grep || echo "(no process found)"
        echo ""
        echo "--- System Resources ---"
        free -h 2>/dev/null || echo "(free not available)"
        df -h / 2>/dev/null || echo "(df not available)"
        echo ""
        echo "--- Uptime ---"
        uptime
        echo ""
        echo "--- Recent Logs (last 80 lines) ---"
        journalctl -u hermes-web-ui --no-pager -n 80 2>/dev/null || echo "(no systemd logs)"
        echo ""
        echo "--- Port Status ---"
        lsof -i :"$PORT" 2>/dev/null || ss -tlnp | grep ":$PORT" || echo "(port not in use)"
        echo ""
        echo "--- Node.js Version ---"
        node --version 2>/dev/null || echo "(node not found)"
    } > "$crash_log" 2>&1

    log "Crash log saved: $crash_log"
    echo "$crash_log"
}

# --- Phase 1: Fast Restart ---
restart_webui() {
    local attempt=$1
    log "Phase 1: Restart attempt $attempt/$MAX_RETRIES"

    # Wait for port to be free
    wait_for_port_free || true

    if [[ -n "$RESTART_CMD" ]]; then
        log "Running custom restart command: $RESTART_CMD"
        eval "$RESTART_CMD" 2>&1 || true
    else
        # Try npm global first (production)
        if command -v hermes-web-ui >/dev/null 2>&1; then
            nohup hermes-web-ui --port "$PORT" > /dev/null 2>&1 &
        # Try local node
        elif [[ -f "dist/server/index.js" ]]; then
            nohup node dist/server/index.js > /dev/null 2>&1 &
        elif [[ -f "$HOME/.npm-global/lib/node_modules/hermes-web-ui/dist/server/index.js" ]]; then
            nohup node "$HOME/.npm-global/lib/node_modules/hermes-web-ui/dist/server/index.js" > /dev/null 2>&1 &
        else
            log "ERROR: No restart method available"
            return 1
        fi
    fi

    # Wait for startup
    local wait_count=0
    while [[ $wait_count -lt 15 ]]; do
        sleep 2
        wait_count=$((wait_count + 1))
        if check_health; then
            log "✅ Phase 1 restart successful (healthy after $((wait_count * 2))s)"
            return 0
        fi
    done

    log "❌ Phase 1 restart failed — not healthy after 30s"
    return 1
}

# --- Phase 2: Auto-Diagnose & Fix ---
diagnose_and_fix() {
    log "🔍 Phase 2: Running auto-diagnosis..."

    local crash_log
    crash_log=$(save_crash_log "Phase 2 diagnosis start" "phase2")
    local log_content
    log_content=$(cat "$crash_log")

    local fixed=false

    # --- Check 1: EADDRINUSE (Port occupied by stale process) ---
    if echo "$log_content" | grep -qi "EADDRINUSE\|address already in use"; then
        log "  🔧 Diagnosis: Port $PORT occupied by stale process"
        local stale_pid
        stale_pid=$(lsof -ti :"$PORT" 2>/dev/null || true)
        if [[ -n "$stale_pid" ]]; then
            log "  Killing stale process: $stale_pid"
            kill "$stale_pid" 2>/dev/null || true
            sleep 2
            kill -9 "$stale_pid" 2>/dev/null || true
            sleep 1
            if restart_webui "diagnose"; then
                fixed=true
                log "  ✅ Fixed: Killed stale process + restarted"
            fi
        fi
    fi

    # --- Check 2: OOM (Out of Memory) ---
    if ! $fixed && echo "$log_content" | grep -qi "out of memory\|OOM\|heap\|JavaScript heap"; then
        log "  🔧 Diagnosis: Out of memory"
        # Clean system memory
        sync && echo 3 > /proc/sys/vm/drop_caches 2>/dev/null || true
        # Kill other heavy processes (not hermes itself)
        local heavy
        heavy=$(ps aux --sort=-%mem | awk 'NR>1 && $6>500000 && !/hermes/ {print $2}' | head -3)
        if [[ -n "$heavy" ]]; then
            log "  Killing heavy processes: $heavy"
            echo "$heavy" | xargs kill 2>/dev/null || true
            sleep 2
        fi
        if restart_webui "diagnose"; then
            fixed=true
            log "  ✅ Fixed: Cleaned memory + restarted"
        fi
    fi

    # --- Check 3: MODULE_NOT_FOUND ---
    if ! $fixed && echo "$log_content" | grep -qi "MODULE_NOT_FOUND\|Cannot find module"; then
        log "  🔧 Diagnosis: Missing module"
        local webui_dir
        webui_dir=$(find /home -name "hermes-web-ui" -type d -path "*/dist/.." 2>/dev/null | head -1)
        if [[ -n "$webui_dir" ]] && [[ -d "$webui_dir" ]]; then
            log "  Reinstalling dependencies in $webui_dir"
            (cd "$webui_dir" && npm install --production 2>&1 | tail -3) || true
            sleep 2
            if restart_webui "diagnose"; then
                fixed=true
                log "  ✅ Fixed: Reinstalled deps + restarted"
            fi
        fi
    fi

    # --- Check 4: EACCES (Permission denied) ---
    if ! $fixed && echo "$log_content" | grep -qi "EACCES\|permission denied"; then
        log "  🔧 Diagnosis: Permission issue"
        chown -R "$(whoami):$(whoami)" "$HOME/.hermes-web-ui/" 2>/dev/null || true
        chmod -R 755 "$HOME/.hermes-web-ui/" 2>/dev/null || true
        if restart_webui "diagnose"; then
            fixed=true
            log "  ✅ Fixed: Fixed permissions + restarted"
        fi
    fi

    # --- Check 5: ENOSPC (Disk full) ---
    if ! $fixed && echo "$log_content" | grep -qi "ENOSPC\|no space left"; then
        log "  🔧 Diagnosis: Disk full"
        # Clean old logs
        find "$LOG_DIR" -name "crash-*.log" -mtime +7 -delete 2>/dev/null || true
        find "$LOG_DIR" -name "*.log" -size +10M -delete 2>/dev/null || true
        # Clean old uploads
        find "$HOME/.hermes-web-ui/upload/" -mtime +30 -type f -delete 2>/dev/null || true
        # Clean systemd journal
        journalctl --vacuum-size=100M 2>/dev/null || true
        if restart_webui "diagnose"; then
            fixed=true
            log "  ✅ Fixed: Cleaned disk + restarted"
        fi
    fi

    # --- Check 6: Upstream Hermes Agent Down ---
    if ! $fixed && echo "$log_content" | grep -qi "ECONNREFUSED\|upstream\|fetch failed"; then
        log "  🔧 Diagnosis: Upstream connection issue"
        # Check common hermes agent ports
        for port in 8642 8643 18789; do
            if curl -s --connect-timeout 2 "http://127.0.0.1:$port/health" >/dev/null 2>&1; then
                log "  Upstream on port $port is alive"
            else
                log "  Upstream on port $port is DOWN"
            fi
        done
        # Try restart anyway — upstream might recover
        if restart_webui "diagnose"; then
            fixed=true
            log "  ✅ Fixed: Restarted (upstream may have recovered)"
        fi
    fi

    # --- Check 7: SyntaxError / TypeError (Code error) ---
    if ! $fixed && echo "$log_content" | grep -qi "SyntaxError\|TypeError\|ReferenceError"; then
        log "  🔧 Diagnosis: Code error detected"
        log "  Attempting rebuild..."
        local webui_dir
        webui_dir=$(find /home -name "hermes-web-ui" -type d -path "*/dist/.." 2>/dev/null | head -1)
        if [[ -n "$webui_dir" ]] && [[ -d "$webui_dir" ]]; then
            (cd "$webui_dir" && npm run build 2>&1 | tail -5) || true
            sleep 2
            if restart_webui "diagnose"; then
                fixed=true
                log "  ✅ Fixed: Rebuilt + restarted"
            fi
        fi
    fi

    # --- Check 8: Corrupted node_modules ---
    if ! $fixed && echo "$log_content" | grep -qi "Cannot find module.*node_modules"; then
        log "  🔧 Diagnosis: Corrupted node_modules"
        local webui_dir
        webui_dir=$(find /home -name "hermes-web-ui" -type d -path "*/dist/.." 2>/dev/null | head -1)
        if [[ -n "$webui_dir" ]] && [[ -d "$webui_dir" ]]; then
            (cd "$webui_dir" && rm -rf node_modules && npm install 2>&1 | tail -3 && npm run build 2>&1 | tail -3) || true
            sleep 2
            if restart_webui "diagnose"; then
                fixed=true
                log "  ✅ Fixed: Clean reinstall + rebuilt + restarted"
            fi
        fi
    fi

    if $fixed; then
        log "✅ Phase 2 diagnosis complete — issue resolved"
        return 0
    else
        log "❌ Phase 2 diagnosis complete — no match or fix failed"
        return 1
    fi
}

# --- Phase 3: Agent Report ---
write_diagnostic_report() {
    local crash_log="$1"
    local timestamp_str
    timestamp_str=$(date '+%Y-%m-%dT%H-%M-%S')

    # Classify error from crash log
    local error_class="UNKNOWN"
    if [[ -f "$crash_log" ]]; then
        local log_content
        log_content=$(cat "$crash_log")
        if echo "$log_content" | grep -qi "EADDRINUSE"; then error_class="PORT_CONFLICT"
        elif echo "$log_content" | grep -qi "out of memory\|OOM\|heap"; then error_class="OOM"
        elif echo "$log_content" | grep -qi "MODULE_NOT_FOUND"; then error_class="MISSING_MODULE"
        elif echo "$log_content" | grep -qi "EACCES\|permission"; then error_class="PERMISSION"
        elif echo "$log_content" | grep -qi "ENOSPC\|no space"; then error_class="DISK_FULL"
        elif echo "$log_content" | grep -qi "SyntaxError\|TypeError\|ReferenceError"; then error_class="CODE_ERROR"
        elif echo "$log_content" | grep -qi "ECONNREFUSED\|fetch failed"; then error_class="UPSTREAM_DOWN"
        fi
    fi

    cat > "$CRASH_SIGNAL" <<EOF
# CRASH RECOVERY SIGNAL
# Generated by watchdog — for agent consumption
# Follow: docs/CRASH-RECOVERY-PROTOCOL.md

CRASH_TIME=$(timestamp)
ERROR_CLASS=$error_class
PHASE1_ATTEMPTS=$MAX_RETRIES
PHASE2_DIAGNOSES=$PHASE2_COUNT
STATUS=AGENT_REVIEW_NEEDED

# Next steps for agent:
# 1. Read latest crash log: ls -t ~/.hermes-web-ui/logs/crash-*.log | head -1 | xargs cat
# 2. Classify error: see ERROR_CLASS above
# 3. Follow docs/CRASH-RECOVERY-PROTOCOL.md for fix recipe
# 4. After fix: rm ~/.hermes-web-ui/logs/CRASH_SIGNAL
# 5. Restart: systemctl restart hermes-web-ui-watchdog
EOF

    log "⚠️  CRASH_SIGNAL written — agent review needed"
    log "   Error class: $error_class"
    log "   Log: $crash_log"
    log "   Protocol: docs/CRASH-RECOVERY-PROTOCOL.md"
}

clear_crash_signal() {
    rm -f "$CRASH_SIGNAL" 2>/dev/null
    rm -f "$DIAGNOSIS_DONE_FILE" 2>/dev/null
}

# --- Main Loop ---
log "Watchdog started (port=$PORT, interval=${CHECK_INTERVAL}s, max_retries=$MAX_RETRIES)"

while true; do
    sleep "$CHECK_INTERVAL"

    # Skip if maintenance mode (during updates)
    if is_maintenance_mode; then
        # Only log once
        if [[ ! -f "$HOME/.hermes-web-ui/.watchdog-muted" ]]; then
            log "⏸️  Maintenance mode active — skipping checks"
            touch "$HOME/.hermes-web-ui/.watchdog-muted"
        fi
        continue
    else
        rm -f "$HOME/.hermes-web-ui/.watchdog-muted" 2>/dev/null
    fi

    # Everything healthy?
    if check_process_alive && check_health; then
        if [[ $CONSECUTIVE_FAILURES -gt 0 ]]; then
            log "✅ Service stable after $CONSECUTIVE_FAILURES recovery"
        fi
        CONSECUTIVE_FAILURES=0
        TOTAL_FAILURES_TODAY=0
        PHASE2_COUNT=0
        clear_crash_signal
        save_state
        continue
    fi

    # --- Service is down ---
    log "⚠️  Service is down! (process=$(check_process_alive && echo alive || echo dead), health=$(check_health 2>/dev/null && echo ok || echo fail))"

    # Save crash log
    local crash_log
    crash_log=$(save_crash_log "Auto-detected failure" "phase1") || true

    CONSECUTIVE_FAILURES=$((CONSECUTIVE_FAILURES + 1))
    TOTAL_FAILURES_TODAY=$((TOTAL_FAILURES_TODAY + 1))
    LAST_CRASH_TIME=$(date +%s)

    # --- Check global circuit breaker ---
    # If too many failures today (across all restart cycles), stop permanently
    if [[ $TOTAL_FAILURES_TODAY -ge 30 ]]; then
        log "🛑 GLOBAL CIRCUIT BREAKER: $TOTAL_FAILURES_TODAY failures today — stopping watchdog"
        log "   Manual intervention required"
        write_diagnostic_report "${crash_log:-unknown}" || true
        save_state
        # Sleep forever — systemd will keep the service alive but watchdog won't do anything
        while true; do
            sleep 3600
        done
    fi

    # --- Phase 1: Fast restart ---
    if [[ $CONSECUTIVE_FAILURES -le $MAX_RETRIES ]]; then
        if restart_webui "$CONSECUTIVE_FAILURES"; then
            CONSECUTIVE_FAILURES=0
            clear_crash_signal
            save_state
            continue
        fi
    fi

    # --- Phase 2: Auto-diagnose ---
    if [[ $PHASE2_COUNT -lt $PHASE2_MAX_DIAGNOSES ]]; then
        PHASE2_COUNT=$((PHASE2_COUNT + 1))
        log "Running Phase 2 diagnosis ($PHASE2_COUNT/$PHASE2_MAX_DIAGNOSES)"

        if diagnose_and_fix; then
            CONSECUTIVE_FAILURES=0
            PHASE2_COUNT=0
            clear_crash_signal
            save_state
            continue
        fi
    fi

    # --- Phase 3: Agent intervention needed ---
    log "🛑 Auto-recovery exhausted. Writing diagnostic report for agent."
    write_diagnostic_report "${crash_log:-unknown}" || true
    save_state

    # Wait before next cycle — give agent time to react
    log "   Sleeping 5 minutes before retry cycle..."
    sleep 300

    # Reset consecutive for next cycle, but keep daily total
    CONSECUTIVE_FAILURES=0
    # Don't reset PHASE2_COUNT — it's bounded by PHASE2_MAX_DIAGNOSES
done
