#!/usr/bin/env bash
#
# hermes-web-ui watchdog — automatic crash recovery with self-healing
#
# Four-phase recovery:
#   Phase 1: Fast restart (simple crashes)
#   Phase 2: Auto-diagnose + targeted fix (known patterns)
#   Phase 3: Agent-triggered repair (unknown errors, fully automatic)
#   Phase 4: Manual intervention report (last resort)
#
# Usage:
#   ./watchdog.sh [options]
#
# Options:
#   --port PORT        Web-UI port (default: 8648)
#   --interval SEC     Check interval in seconds (default: 30)
#   --max-retries N    Max Phase 1 restart attempts (default: 3)
#   --log-dir DIR      Log directory (default: ~/.hermes-web-ui/logs)
#   --restart-cmd CMD  Custom restart command
#   --state-file PATH  Persistent state (default: ~/.hermes-web-ui/watchdog-state)
#   --agent-timeout SEC  Agent repair timeout (default: 300)
#   --dry-run          Only detect, don't restart
#

set -euo pipefail

# --- Defaults ---
PORT="${PORT:-8648}"
CHECK_INTERVAL="${CHECK_INTERVAL:-30}"
MAX_RETRIES="${MAX_RETRIES:-3}"
LOG_DIR="${LOG_DIR:-$HOME/.hermes-web-ui/logs}"
STATE_FILE="${STATE_FILE:-$HOME/.hermes-web-ui/watchdog-state}"
RESTART_CMD="${RESTART_CMD:-}"
HEALTH_URL="http://127.0.0.1:${PORT}/health"
MAINTENANCE_FILE="$HOME/.hermes-web-ui/.maintenance"
AGENT_TIMEOUT="${AGENT_TIMEOUT:-300}"
DRY_RUN=false

# --- Phase config ---
PHASE2_MAX_DIAGNOSES=3   # Max Phase 2 attempts per day
PHASE3_MAX_ATTEMPTS=2    # Max Phase 3 agent triggers per day
DAILY_GLOBAL_LIMIT=30    # Hard stop: total failures per day

# --- Parse CLI args ---
while [[ $# -gt 0 ]]; do
    case $1 in
        --port) PORT="$2"; HEALTH_URL="http://127.0.0.1:${PORT}/health"; shift 2 ;;
        --interval) CHECK_INTERVAL="$2"; shift 2 ;;
        --max-retries) MAX_RETRIES="$2"; shift 2 ;;
        --log-dir) LOG_DIR="$2"; shift 2 ;;
        --restart-cmd) RESTART_CMD="$2"; shift 2 ;;
        --state-file) STATE_FILE="$2"; shift 2 ;;
        --agent-timeout) AGENT_TIMEOUT="$2"; shift 2 ;;
        --dry-run) DRY_RUN=true; shift ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

# --- Setup ---
mkdir -p "$LOG_DIR" "$(dirname "$STATE_FILE")"
CRASH_SIGNAL="$LOG_DIR/CRASH_SIGNAL"
CONSECUTIVE_FAILURES=0
TOTAL_FAILURES_TODAY=0
PHASE2_COUNT=0
PHASE3_COUNT=0
LAST_RESET_DATE=""

# Load persistent state
if [[ -f "$STATE_FILE" ]]; then
    # shellcheck source=/dev/null
    source "$STATE_FILE" 2>/dev/null || true
fi

# Reset daily counter
TODAY=$(date '+%Y-%m-%d')
if [[ "${LAST_RESET_DATE:-}" != "$TODAY" ]]; then
    TOTAL_FAILURES_TODAY=0
    PHASE2_COUNT=0
    PHASE3_COUNT=0
fi

save_state() {
    cat > "$STATE_FILE" <<EOF
# Auto-generated by watchdog — do not edit
TOTAL_FAILURES_TODAY=$TOTAL_FAILURES_TODAY
PHASE2_COUNT=$PHASE2_COUNT
PHASE3_COUNT=$PHASE3_COUNT
LAST_RESET_DATE=$TODAY
LAST_CRASH_TIME=${LAST_CRASH_TIME:-0}
EOF
}

# --- Functions ---
timestamp() { date '+%Y-%m-%d %H:%M:%S'; }

log() {
    echo "[$(timestamp)] [watchdog] $*"
}

is_maintenance_mode() {
    [[ -f "$MAINTENANCE_FILE" ]]
}

check_process_alive() {
    pgrep -f "hermes-web-ui.*dist/server" >/dev/null 2>&1
}

check_health() {
    local http_code
    http_code=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout 5 --max-time 10 "$HEALTH_URL" 2>/dev/null || echo "000")
    [[ "$http_code" == "200" ]]
}

wait_for_port_free() {
    local max_wait=10
    local waited=0
    while [[ $waited -lt $max_wait ]]; do
        if ! lsof -i :"$PORT" >/dev/null 2>&1; then
            return 0
        fi
        sleep 1
        waited=$((waited + 1))
    done
    log "⚠️  Port $PORT still occupied after ${max_wait}s"
    return 1
}

save_crash_log() {
    local reason="$1"
    local phase="$2"
    local timestamp_str
    timestamp_str=$(date '+%Y-%m-%dT%H-%M-%S')
    local crash_log="$LOG_DIR/crash-${timestamp_str}.log"

    {
        echo "=== Crash Report ==="
        echo "Time: $(timestamp)"
        echo "Reason: $reason"
        echo "Phase: $phase"
        echo ""
        echo "--- Process Status ---"
        ps aux | grep -E "hermes-web-ui|node.*${PORT}" | grep -v grep || echo "(no process found)"
        echo ""
        echo "--- System Resources ---"
        free -h 2>/dev/null || echo "(free not available)"
        df -h / 2>/dev/null || echo "(df not available)"
        echo ""
        echo "--- Uptime ---"
        uptime
        echo ""
        echo "--- Recent Logs (last 80 lines) ---"
        journalctl -u hermes-web-ui --no-pager -n 80 2>/dev/null || echo "(no systemd logs)"
        echo ""
        echo "--- Port Status ---"
        lsof -i :"$PORT" 2>/dev/null || ss -tlnp | grep ":$PORT" || echo "(port not in use)"
        echo ""
        echo "--- Node.js Version ---"
        node --version 2>/dev/null || echo "(node not found)"
    } > "$crash_log" 2>&1

    log "Crash log saved: $crash_log"
    echo "$crash_log"
}

# --- Phase 1: Fast Restart ---
restart_webui() {
    local attempt=$1
    log "Phase 1: Restart attempt $attempt/$MAX_RETRIES"

    if $DRY_RUN; then
        log "  [DRY RUN] Would restart web-ui"
        return 1
    fi

    # Wait for port to be free
    wait_for_port_free || true

    if [[ -n "$RESTART_CMD" ]]; then
        log "Running custom restart command: $RESTART_CMD"
        eval "$RESTART_CMD" 2>&1 || true
    else
        # Try npm global first (production)
        if command -v hermes-web-ui >/dev/null 2>&1; then
            nohup hermes-web-ui --port "$PORT" > /dev/null 2>&1 &
        # Try local node
        elif [[ -f "dist/server/index.js" ]]; then
            nohup node dist/server/index.js > /dev/null 2>&1 &
        elif [[ -f "$HOME/.npm-global/lib/node_modules/hermes-web-ui/dist/server/index.js" ]]; then
            nohup node "$HOME/.npm-global/lib/node_modules/hermes-web-ui/dist/server/index.js" > /dev/null 2>&1 &
        else
            log "ERROR: No restart method available"
            return 1
        fi
    fi

    # Wait for startup
    local wait_count=0
    while [[ $wait_count -lt 15 ]]; do
        sleep 2
        wait_count=$((wait_count + 1))
        if check_health; then
            log "✅ Phase 1 restart successful (healthy after $((wait_count * 2))s)"
            return 0
        fi
    done

    log "❌ Phase 1 restart failed — not healthy after 30s"
    return 1
}

# --- Phase 2: Auto-Diagnose & Fix ---
diagnose_and_fix() {
    log "🔍 Phase 2: Running auto-diagnosis..."

    local crash_log
    crash_log=$(save_crash_log "Phase 2 diagnosis start" "phase2")
    local log_content
    log_content=$(cat "$crash_log")

    local fixed=false

    # --- Check 1: EADDRINUSE (Port occupied by stale process) ---
    if echo "$log_content" | grep -qi "EADDRINUSE\|address already in use"; then
        log "  🔧 Diagnosis: Port $PORT occupied by stale process"
        local stale_pid
        stale_pid=$(lsof -ti :"$PORT" 2>/dev/null || true)
        if [[ -n "$stale_pid" ]]; then
            log "  Killing stale process: $stale_pid"
            kill "$stale_pid" 2>/dev/null || true
            sleep 2
            kill -9 "$stale_pid" 2>/dev/null || true
            sleep 1
            if restart_webui "diagnose"; then
                fixed=true
                log "  ✅ Fixed: Killed stale process + restarted"
            fi
        fi
    fi

    # --- Check 2: OOM (Out of Memory) ---
    if ! $fixed && echo "$log_content" | grep -qi "out of memory\|OOM\|heap\|JavaScript heap"; then
        log "  🔧 Diagnosis: Out of memory"
        sync && echo 3 > /proc/sys/vm/drop_caches 2>/dev/null || true
        local heavy
        heavy=$(ps aux --sort=-%mem | awk 'NR>1 && $6>500000 && !/hermes/ {print $2}' | head -3)
        if [[ -n "$heavy" ]]; then
            log "  Killing heavy processes: $heavy"
            echo "$heavy" | xargs kill 2>/dev/null || true
            sleep 2
        fi
        if restart_webui "diagnose"; then
            fixed=true
            log "  ✅ Fixed: Cleaned memory + restarted"
        fi
    fi

    # --- Check 3: MODULE_NOT_FOUND ---
    if ! $fixed && echo "$log_content" | grep -qi "MODULE_NOT_FOUND\|Cannot find module"; then
        log "  🔧 Diagnosis: Missing module"
        local webui_dir
        webui_dir=$(find /home -name "hermes-web-ui" -type d -path "*/dist/.." 2>/dev/null | head -1)
        if [[ -n "$webui_dir" ]] && [[ -d "$webui_dir" ]]; then
            log "  Reinstalling dependencies in $webui_dir"
            (cd "$webui_dir" && npm install --production 2>&1 | tail -3) || true
            sleep 2
            if restart_webui "diagnose"; then
                fixed=true
                log "  ✅ Fixed: Reinstalled deps + restarted"
            fi
        fi
    fi

    # --- Check 4: EACCES (Permission denied) ---
    if ! $fixed && echo "$log_content" | grep -qi "EACCES\|permission denied"; then
        log "  🔧 Diagnosis: Permission issue"
        chown -R "$(whoami):$(whoami)" "$HOME/.hermes-web-ui/" 2>/dev/null || true
        chmod -R 755 "$HOME/.hermes-web-ui/" 2>/dev/null || true
        if restart_webui "diagnose"; then
            fixed=true
            log "  ✅ Fixed: Fixed permissions + restarted"
        fi
    fi

    # --- Check 5: ENOSPC (Disk full) ---
    if ! $fixed && echo "$log_content" | grep -qi "ENOSPC\|no space left"; then
        log "  🔧 Diagnosis: Disk full"
        find "$LOG_DIR" -name "crash-*.log" -mtime +7 -delete 2>/dev/null || true
        find "$LOG_DIR" -name "*.log" -size +10M -delete 2>/dev/null || true
        find "$HOME/.hermes-web-ui/upload/" -mtime +30 -type f -delete 2>/dev/null || true
        journalctl --vacuum-size=100M 2>/dev/null || true
        if restart_webui "diagnose"; then
            fixed=true
            log "  ✅ Fixed: Cleaned disk + restarted"
        fi
    fi

    # --- Check 6: Upstream Hermes Agent Down ---
    if ! $fixed && echo "$log_content" | grep -qi "ECONNREFUSED\|upstream\|fetch failed"; then
        log "  🔧 Diagnosis: Upstream connection issue"
        for port in 8642 8643 18789; do
            if curl -s --connect-timeout 2 "http://127.0.0.1:$port/health" >/dev/null 2>&1; then
                log "  Upstream on port $port is alive"
            else
                log "  Upstream on port $port is DOWN"
            fi
        done
        if restart_webui "diagnose"; then
            fixed=true
            log "  ✅ Fixed: Restarted (upstream may have recovered)"
        fi
    fi

    # --- Check 7: SyntaxError / TypeError (Code error) ---
    if ! $fixed && echo "$log_content" | grep -qi "SyntaxError\|TypeError\|ReferenceError"; then
        log "  🔧 Diagnosis: Code error detected"
        log "  Attempting rebuild..."
        local webui_dir
        webui_dir=$(find /home -name "hermes-web-ui" -type d -path "*/dist/.." 2>/dev/null | head -1)
        if [[ -n "$webui_dir" ]] && [[ -d "$webui_dir" ]]; then
            (cd "$webui_dir" && npm run build 2>&1 | tail -5) || true
            sleep 2
            if restart_webui "diagnose"; then
                fixed=true
                log "  ✅ Fixed: Rebuilt + restarted"
            fi
        fi
    fi

    # --- Check 8: Corrupted node_modules ---
    if ! $fixed && echo "$log_content" | grep -qi "Cannot find module.*node_modules"; then
        log "  🔧 Diagnosis: Corrupted node_modules"
        local webui_dir
        webui_dir=$(find /home -name "hermes-web-ui" -type d -path "*/dist/.." 2>/dev/null | head -1)
        if [[ -n "$webui_dir" ]] && [[ -d "$webui_dir" ]]; then
            (cd "$webui_dir" && rm -rf node_modules && npm install 2>&1 | tail -3 && npm run build 2>&1 | tail -3) || true
            sleep 2
            if restart_webui "diagnose"; then
                fixed=true
                log "  ✅ Fixed: Clean reinstall + rebuilt + restarted"
            fi
        fi
    fi

    if $fixed; then
        log "✅ Phase 2 diagnosis complete — issue resolved"
        return 0
    else
        log "❌ Phase 2 diagnosis complete — no match or fix failed"
        return 1
    fi
}

# --- Phase 3: Agent-Triggered Repair ---
# Check if hermes-agent CLI is available and its API server is running
detect_hermes_agent() {
    # Check if hermes CLI is installed
    if ! command -v hermes >/dev/null 2>&1; then
        log "  hermes CLI not found in PATH"
        return 1
    fi

    # Check if hermes agent is running (try common ports)
    for port in 8015 18789 8642 8643; do
        if curl -s --connect-timeout 2 "http://127.0.0.1:$port/health" >/dev/null 2>&1; then
            log "  Hermes agent detected on port $port"
            return 0
        fi
    done

    # Check if hermes process is running even if health endpoint is missing
    if pgrep -f "hermes.*(agent|gateway|run_agent)" >/dev/null 2>&1; then
        log "  Hermes agent process detected (no health endpoint)"
        return 0
    fi

    log "  No hermes agent detected"
    return 1
}

# Try to start hermes agent if it's down
try_start_hermes_agent() {
    log "  Attempting to start hermes agent..."

    # Try systemd first
    if systemctl --user start hermes-gateway 2>/dev/null; then
        log "  Started via systemctl"
        sleep 5
        return 0
    fi

    # Try nohup
    if command -v hermes >/dev/null 2>&1; then
        nohup hermes gateway run > /dev/null 2>&1 &
        sleep 5
        if detect_hermes_agent; then
            log "  Started via nohup"
            return 0
        fi
    fi

    log "  ❌ Failed to start hermes agent"
    return 1
}

trigger_agent_repair() {
    log "🤖 Phase 3: Triggering agent auto-repair..."

    local crash_log="$1"
    local error_class="$2"

    # Build the diagnostic context for the agent
    local crash_log_content=""
    if [[ -f "$crash_log" ]]; then
        crash_log_content=$(tail -100 "$crash_log" 2>/dev/null || echo "")
    fi

    # Run standalone diagnosis for structured output
    local diagnosis_output=""
    local diagnose_script="$HOME/.hermes-web-ui/crash-diagnose.sh"
    if [[ -x "$diagnose_script" ]]; then
        diagnosis_output=$("$diagnose_script" --json 2>/dev/null || echo "{}")
    fi

    # Check if hermes agent is available
    if ! detect_hermes_agent; then
        log "  Hermes agent not available — attempting to start..."
        if try_start_hermes_agent; then
            log "  Agent started successfully"
        else
            log "  ❌ Cannot start agent — falling through to Phase 4"
            return 1
        fi
    fi

    # Write the repair prompt
    local repair_prompt
    repair_prompt=$(cat <<PROMPT
## Web-UI Crash Auto-Repair Task

The hermes-web-ui service has crashed and automated recovery (Phase 1 & 2) failed.
You are being called to diagnose and fix the issue automatically.

### Error Classification: ${error_class}

### Diagnosis Output:
${diagnosis_output}

### Crash Log (last 100 lines):
\`\`\`
${crash_log_content}
\`\`\`

### Instructions:
1. Read the crash recovery protocol: docs/CRASH-RECOVERY-PROTOCOL.md
2. Read the latest crash log: \$(ls -t ~/.hermes-web-ui/logs/crash-*.log | head -1 | xargs cat)
3. Check system resources: free -h && df -h / && uptime
4. Based on error class "${error_class}", apply the appropriate fix from the protocol
5. After fixing, verify the service is healthy: curl -s http://127.0.0.1:${PORT}/health
6. If fixed, clean up: rm -f ~/.hermes-web-ui/logs/CRASH_SIGNAL
7. Report what you did and whether it succeeded

### Important:
- Follow the CRASH-RECOVERY-PROTOCOL.md strictly
- Do NOT modify source code unless absolutely necessary
- Prefer reinstall/rebuild over code changes
- After any restart, always verify health endpoint responds 200
PROMPT
)

    # Call hermes agent with the repair prompt
    log "  Sending repair request to agent (timeout: ${AGENT_TIMEOUT}s)..."

    local agent_output=""
    local agent_exit=1

    # Use hermes chat -q (non-interactive mode) with timeout
    agent_output=$(timeout "$AGENT_TIMEOUT" hermes chat --yolo -q "$repair_prompt" 2>&1) || agent_exit=$?

    if [[ $agent_exit -eq 0 ]]; then
        log "✅ Phase 3: Agent repair completed successfully"
        log "  Agent output (last 5 lines):"
        echo "$agent_output" | tail -5 | while IFS= read -r line; do
            log "    $line"
        done

        # Verify if web-ui is actually back
        sleep 5
        if check_health; then
            log "✅ Phase 3: Web-ui confirmed healthy after agent repair"
            return 0
        else
            log "⚠️  Phase 3: Agent completed but web-ui still not healthy"
            return 1
        fi
    elif [[ $agent_exit -eq 124 ]]; then
        log "❌ Phase 3: Agent repair timed out after ${AGENT_TIMEOUT}s"
        return 1
    else
        log "❌ Phase 3: Agent repair failed (exit code: $agent_exit)"
        log "  Agent output (last 10 lines):"
        echo "$agent_output" | tail -10 | while IFS= read -r line; do
            log "    $line"
        done
        return 1
    fi
}

# --- Phase 4: Manual Intervention Report ---
write_diagnostic_report() {
    local crash_log="$1"
    local error_class="$2"
    local timestamp_str
    timestamp_str=$(date '+%Y-%m-%dT%H-%M-%S')

    cat > "$CRASH_SIGNAL" <<EOF
# CRASH RECOVERY SIGNAL
# Generated by watchdog — ALL automatic recovery phases failed
# This requires manual intervention

CRASH_TIME=$(timestamp)
ERROR_CLASS=$error_class
PHASE1_ATTEMPTS=$MAX_RETRIES
PHASE2_DIAGNOSES=$PHASE2_COUNT
PHASE3_AGENT_ATTEMPTS=$PHASE3_COUNT
STATUS=MANUAL_INTERVENTION_NEEDED

## Recovery Summary:
# Phase 1 (Fast Restart): Failed $MAX_RETRIES attempts
# Phase 2 (Auto-Diagnose): Ran $PHASE2_COUNT diagnoses, no fix worked
# Phase 3 (Agent Repair): Triggered $PHASE3_COUNT times, agent could not fix

## Next steps for manual intervention:
# 1. Read latest crash log: ls -t ~/.hermes-web-ui/logs/crash-*.log | head -1 | xargs cat
# 2. Run diagnosis: bash ~/.hermes-web-ui/crash-diagnose.sh
# 3. Classify error: see ERROR_CLASS above
# 4. Follow docs/CRASH-RECOVERY-PROTOCOL.md for fix recipe
# 5. After fix: rm ~/.hermes-web-ui/logs/CRASH_SIGNAL
# 6. Restart watchdog: systemctl --user restart hermes-web-ui-watchdog
EOF

    log "⚠️  CRASH_SIGNAL written — manual intervention needed"
    log "   Error class: $error_class"
    log "   Log: $crash_log"
}

clear_crash_signal() {
    rm -f "$CRASH_SIGNAL" 2>/dev/null
}

# --- Main Loop ---
log "Watchdog started (port=$PORT, interval=${CHECK_INTERVAL}s, max_retries=$MAX_RETRIES, agent_timeout=${AGENT_TIMEOUT}s)"
log "Phase 3 auto-repair: $(command -v hermes >/dev/null 2>&1 && echo 'ENABLED' || echo 'DISABLED (hermes not found)')"

while true; do
    sleep "$CHECK_INTERVAL"

    # Skip if maintenance mode (during updates)
    if is_maintenance_mode; then
        if [[ ! -f "$HOME/.hermes-web-ui/.watchdog-muted" ]]; then
            log "⏸️  Maintenance mode active — skipping checks"
            touch "$HOME/.hermes-web-ui/.watchdog-muted"
        fi
        continue
    else
        rm -f "$HOME/.hermes-web-ui/.watchdog-muted" 2>/dev/null
    fi

    # Everything healthy?
    if check_process_alive && check_health; then
        if [[ $CONSECUTIVE_FAILURES -gt 0 ]]; then
            log "✅ Service stable after $CONSECUTIVE_FAILURES recovery attempts"
        fi
        CONSECUTIVE_FAILURES=0
        TOTAL_FAILURES_TODAY=0
        PHASE2_COUNT=0
        PHASE3_COUNT=0
        clear_crash_signal
        save_state
        continue
    fi

    # --- Service is down ---
    log "⚠️  Service is down! (process=$(check_process_alive && echo alive || echo dead), health=$(check_health 2>/dev/null && echo ok || echo fail))"

    # Save crash log
    crash_log=$(save_crash_log "Auto-detected failure" "phase1") || true

    CONSECUTIVE_FAILURES=$((CONSECUTIVE_FAILURES + 1))
    TOTAL_FAILURES_TODAY=$((TOTAL_FAILURES_TODAY + 1))
    LAST_CRASH_TIME=$(date +%s)

    # --- Check global circuit breaker ---
    if [[ $TOTAL_FAILURES_TODAY -ge $DAILY_GLOBAL_LIMIT ]]; then
        log "🛑 GLOBAL CIRCUIT BREAKER: $TOTAL_FAILURES_TODAY failures today — stopping watchdog"
        log "   Manual intervention required"
        write_diagnostic_report "${crash_log:-unknown}" "CIRCUIT_BREAKER" || true
        save_state
        while true; do
            sleep 3600
        done
    fi

    # --- Classify error from crash log ---
    error_class="UNKNOWN"
    if [[ -f "$crash_log" ]]; then
        local log_content
        log_content=$(cat "$crash_log")
        if echo "$log_content" | grep -qi "EADDRINUSE"; then error_class="PORT_CONFLICT"
        elif echo "$log_content" | grep -qi "out of memory\|OOM\|heap"; then error_class="OOM"
        elif echo "$log_content" | grep -qi "MODULE_NOT_FOUND"; then error_class="MISSING_MODULE"
        elif echo "$log_content" | grep -qi "EACCES\|permission"; then error_class="PERMISSION"
        elif echo "$log_content" | grep -qi "ENOSPC\|no space"; then error_class="DISK_FULL"
        elif echo "$log_content" | grep -qi "SyntaxError\|TypeError\|ReferenceError"; then error_class="CODE_ERROR"
        elif echo "$log_content" | grep -qi "ECONNREFUSED\|fetch failed"; then error_class="UPSTREAM_DOWN"
        fi
    fi

    # --- Phase 1: Fast restart ---
    if [[ $CONSECUTIVE_FAILURES -le $MAX_RETRIES ]]; then
        if restart_webui "$CONSECUTIVE_FAILURES"; then
            CONSECUTIVE_FAILURES=0
            clear_crash_signal
            save_state
            continue
        fi
    fi

    # --- Phase 2: Auto-diagnose ---
    if [[ $PHASE2_COUNT -lt $PHASE2_MAX_DIAGNOSES ]]; then
        PHASE2_COUNT=$((PHASE2_COUNT + 1))
        log "Running Phase 2 diagnosis ($PHASE2_COUNT/$PHASE2_MAX_DIAGNOSES)"

        if diagnose_and_fix; then
            CONSECUTIVE_FAILURES=0
            PHASE2_COUNT=0
            clear_crash_signal
            save_state
            continue
        fi
    fi

    # --- Phase 3: Agent-triggered repair ---
    if [[ $PHASE3_COUNT -lt $PHASE3_MAX_ATTEMPTS ]]; then
        PHASE3_COUNT=$((PHASE3_COUNT + 1))
        log "Running Phase 3 agent repair ($PHASE3_COUNT/$PHASE3_MAX_ATTEMPTS)"

        if trigger_agent_repair "${crash_log:-unknown}" "$error_class"; then
            CONSECUTIVE_FAILURES=0
            PHASE2_COUNT=0
            PHASE3_COUNT=0
            clear_crash_signal
            save_state
            continue
        fi
    fi

    # --- Phase 4: Manual intervention needed ---
    log "🛑 All automatic recovery phases exhausted. Manual intervention needed."
    write_diagnostic_report "${crash_log:-unknown}" "$error_class" || true
    save_state

    # Sleep before next full cycle
    log "   Sleeping 10 minutes before next full recovery cycle..."
    sleep 600

    # Reset for next cycle (keep daily total)
    CONSECUTIVE_FAILURES=0
    # Don't reset PHASE2_COUNT or PHASE3_COUNT — bounded by max
done
